# Tugas 1

In [ ]:
import pandas as pd
import math

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/febyfadlilah/dataset/main/StudentsPerformance.csv")

In [ ]:
data

,gender,race,parental_level,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,none,72,72,74
1,female,group C,some college,completed,69,90,88
2,female,group B,master's degree,none,90,95,93
3,male,group A,associate's degree,none,47,57,44
4,male,group C,some college,none,76,78,75
...,...,...,...,...,...,...,...
995,female,group E,master's degree,completed,88,99,95
996,male,group C,high school,none,62,55,55
997,female,group C,high school,completed,59,71,65
998,female,group D,some college,completed,68,78,77
999,female,group D,some college,none,77,86,86

In [ ]:
# menampilkan dataset shape
no_kolom = data.shape[1]

In [ ]:
# menampilkan semua kolom pada data set
pd.set_option('display.max_columns', no_kolom)
pd.set_option('display.max_rows', no_kolom)
#menampilkan semua kolom dari dataframe
data.columns

Index(['gender', 'race', 'parental_level', 'test_preparation_course',
       'math_score', 'reading_score', 'writing_score'],
      dtype='object')

### **Menghitung Biner**

In [ ]:
data[["gender","test_preparation_course"]].head()

   gender test_preparation_course
0  female                    none
1  female               completed
2  female                    none
3    male                    none
4    male                    none

In [ ]:
#code gendernya
cowo = "male"
cewe = "female"
lulus = "completed"
tdk_lulus = "none"

#nilai konversi biner
value_of_one = 1
value_of_zero = 0

def change_biner(gender):
  return value_of_one if gender == cowo else value_of_zero
def change_binertes(test_preparation_course):
  return value_of_one if test_preparation_course == lulus else value_of_zero

In [ ]:
#Update Nilai dari Gender dan Test Preparation
data['gender'] = data['gender'].apply(change_biner)
data['test_preparation_course']= data['test_preparation_course'].apply(change_binertes)

In [ ]:
data[["gender","test_preparation_course"]].head()

   gender  test_preparation_course
0       0                        0
1       0                        1
2       0                        0
3       1                        0
4       1                        0

**Menghitung Biner Simetris**

In [ ]:
def binersimetris(i,j):
  q=r=s=t=0
  for col in ['gender','test_preparation_course']:
    if data[col][i]==1 and data[col][j] == 1:
      q+=1
    elif data[col][i]==1 and data[col][j]==0:
      r+=1
    elif data[col][i]==0 and data[col][j] == 1:
      s+=1
    else :
      t+=1
  return (r+s)/(q+r+s+t)

In [ ]:
binersimetris(1,2)

0.0

In [ ]:
binersimetris(1,3)

0.0

In [ ]:
binersimetris(1,4)

0.0

**Menghitung Biner Asimetris**

In [ ]:
def binerii(i,j):
  q=r=s=0
  for col in ['gender','test_preparation_course']:
    if data[col][i]==1 and data[col][j] == 1:
      q+=1
    elif data[col][i]==1 and data[col][j]==0:
      r+=1
    elif data[col][i]==0 and data[col][j] == 1:
      s+=1
  return (r+s)/(q+r+s)

### **Menghitung Data Nominal**

In [ ]:
data[["race","parental_level"]].head()

      race      parental_level
0  group B   bachelor's degree
1  group C        some college
2  group B     master's degree
3  group A  associate's degree
4  group C        some college

In [ ]:
# Menghitung jarak data Nominal
def d1(i,j):
    P = 4
    M = 0
    for col in ["race","parental_level"]:
        if data[col][i] == data[col][j]:
            M += 1

    return (P-M)/P

In [ ]:
# Menampilkan hasil perhitungan
print(d1(1,2))
print(d1(1,3))
print(d1(1,4))

1.0
1.0
0.5

### **Menghitung Data Numeric**

In [ ]:
data[["math_score","reading_score","writing_score"]].head()

   math_score  reading_score  writing_score
0          72             72             74
1          69             90             88
2          90             95             93
3          47             57             44
4          76             78             75

In [ ]:
data.describe()

,gender,test_preparation_course,math_score,reading_score,writing_score
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,0.482000,0.358000,66.08900,69.169000,68.054000
std,0.499926,0.479652,15.16308,14.600192,15.195657
...,...,...,...,...,...
50%,0.000000,0.000000,66.00000,70.000000,69.000000
75%,1.000000,1.000000,77.00000,79.000000,79.000000
max,1.000000,1.000000,100.00000,100.000000,100.000000

In [ ]:
#normalisasi math score
std1 = 15.16308
mean1 = 66.08900
for col1 in ['math_score']:
  data1 = data[col1]
  hasil1 = (data1-mean1)/std1
  print(hasil1)
#normalisasi reading_score
std2 = 14.600192
mean2 = 68.054000
for col2 in ['reading_score']:
  data2 = data[col2]
  hasil2 = (data2-mean2)/std2
  print(hasil2)

#normalisasi writing_score
std3 = 15.195657
mean3 = 68.054000
for col3 in ['writing_score']:
  data3 = data[col3]
  hasil3 = (data3-mean3)/std3
  print(hasil3)

0      0.389828
1      0.191979
2      1.576922
         ...
997   -0.467517
998    0.126030
999    0.719577
Name: math_score, Length: 1000, dtype: float64
0      0.270270
1      1.503131
2      1.845592
         ...
997    0.201778
998    0.681224
999    1.229162
Name: reading_score, Length: 1000, dtype: float64
0      0.391296
1      1.312612
2      1.641653
         ...
997   -0.200978
998    0.588721
999    1.180995
Name: writing_score, Length: 1000, dtype: float64

In [ ]:
# Menghitung jarak Numeric dengan metode Euclidean
def d2(x,y,h):
    result = 0
    for col in [hasil1, hasil2, hasil3]:
        result = math.pow(abs(col[x] - col[y]), h)
    return result**(1/h)

In [ ]:
# Hasil perhitungan
print(d2(1,2,2))
print(d2(1,3,2))
print(d2(1,4,2))

0.32904138333735755
2.895564173368746
0.8555075966771294

### **Similarity**

In [ ]:
# Jarak d(1,2)
print(d1(1,2)+d2(1,2,2)+binersimetris(1,2))

1.3290413833373576

In [ ]:
# Jarak d(1,3)
print(d1(1,3)+d2(1,3,2)+binersimetris(1,3))

3.895564173368746

In [ ]:
# Jarak d(1,4)
print(d1(1,4)+d2(1,4,2)+binersimetris(1,4))

1.3555075966771293

### **Diskritisasi**

In [6]:
import pandas as pd
import math

In [2]:
ds = pd.read_csv("https://raw.githubusercontent.com/febyfadlilah/dataset/main/IRIS.csv")

In [3]:
ds

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
ds[["sepal_length","sepal_width","petal_length","petal_width"]]

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [5]:
ds.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [43]:
a = 7.9
b = 4.3
#diskritisasi sepal_length
w1 = (a-b)/4
w1

0.9000000000000001

In [44]:
v1 = b + w1
v1

5.2

In [45]:
v2 = b + (2*w1)
v2

6.1

In [46]:
v3 = b + (3*w1)
v3

7.0

In [47]:
v4 = b + (4*w1)
v4

7.9

In [50]:
for col1 in ['sepal_length']:
    data1 = ds[col1]
def changekat(data1) :
    if data1 >= b and data1 < v1 :
      return "A"
    elif data1 >= v1 and data1 < v2 :
      return "B"
    elif data1 >= v2 and data1 < v3 :
      return "C"
    elif data1 >= v3 and data1 < v4 :
      return "D"

In [89]:
data1

0      A
1      A
2      A
3      A
4      A
      ..
145    C
146    C
147    C
148    C
149    B
Name: sepal_length, Length: 150, dtype: object

In [90]:
ds

    sepal_length  sepal_width  petal_length  petal_width         species
0              A          3.5           1.4          0.2     Iris-setosa
1              A          3.0           1.4          0.2     Iris-setosa
2              A          3.2           1.3          0.2     Iris-setosa
3              A          3.1           1.5          0.2     Iris-setosa
4              A          3.6           1.4          0.2     Iris-setosa
..           ...          ...           ...          ...             ...
145            C          3.0           5.2          2.3  Iris-virginica
146            C          2.5           5.0          1.9  Iris-virginica
147            C          3.0           5.2          2.0  Iris-virginica
148            C          3.4           5.4          2.3  Iris-virginica
149            B          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [56]:
#diskritisasi sepal width
x = 4.4
y = 2
w2 = (x-y)/4
w2

0.6000000000000001

In [59]:
v11 = y + w2
v11

2.6

In [60]:
v12 = y + (2*w2)
v12

3.2

In [61]:
v13 = y + (3*w2)
v13

3.8000000000000003

In [62]:
v14 = y + (4*w2)
v14

4.4

In [63]:
for col2 in ['sepal_width']:
    data2 = ds[col2]
def changekat2(data2) :
    if data2 >= y and data2 < v11 :
      return "A"
    elif data2 >= v11 and data2 < v12 :
      return "B"
    elif data2 >= v12 and data2 < v13 :
      return "C"
    elif data2 >= v13 and data2 < v14 :
      return "D"

In [91]:
data2

0      C
1      B
2      C
3      B
4      C
      ..
145    B
146    A
147    B
148    C
149    B
Name: sepal_width, Length: 150, dtype: object

In [98]:
ds

    sepal_length  sepal_width  petal_length  petal_width         species
0              A          3.5           1.4          0.2     Iris-setosa
1              A          3.0           1.4          0.2     Iris-setosa
2              A          3.2           1.3          0.2     Iris-setosa
3              A          3.1           1.5          0.2     Iris-setosa
4              A          3.6           1.4          0.2     Iris-setosa
..           ...          ...           ...          ...             ...
145            C          3.0           5.2          2.3  Iris-virginica
146            C          2.5           5.0          1.9  Iris-virginica
147            C          3.0           5.2          2.0  Iris-virginica
148            C          3.4           5.4          2.3  Iris-virginica
149            B          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]