# Tugas 7 - Analisis Data Nasabah

In [ ]:
#import lybrary
import pandas as pd
import math

In [ ]:
data = pd.read_excel("https://raw.githubusercontent.com/febyfadlilah/dataset/main/credit_score.xlsx")

In [ ]:
data

,Unnamed: 0,kode_kontrak,pendapatan_setahun_juta,kpr_aktif,durasi_pinjaman_bulan,jumlah_tanggungan,rata_rata_overdue,risk_rating
0,1,AGR-000001,295,YA,48,5,61 - 90 days,4
1,2,AGR-000011,271,YA,36,5,61 - 90 days,4
2,3,AGR-000030,159,TIDAK,12,0,0 - 30 days,1
3,4,AGR-000043,210,YA,12,3,46 - 60 days,3
4,5,AGR-000049,165,TIDAK,36,0,31 - 45 days,2
...,...,...,...,...,...,...,...,...
895,896,AGR-010739,112,YA,48,5,> 90 days,5
896,897,AGR-010744,120,YA,48,2,46 - 60 days,3
897,898,AGR-010758,166,TIDAK,24,2,0 - 30 days,1
898,899,AGR-010775,196,TIDAK,48,0,31 - 45 days,2
899,900,AGR-010790,204,TIDAK,24,2,0 - 30 days,1

In [ ]:
data2 = data[["kpr_aktif"]]

In [ ]:
data2

    kpr_aktif
0          YA
1          YA
2       TIDAK
3          YA
4       TIDAK
..        ...
895        YA
896        YA
897     TIDAK
898     TIDAK
899     TIDAK

[900 rows x 1 columns]

In [ ]:
aktif = pd.get_dummies(data2)

In [ ]:
data3 = data[["rata_rata_overdue"]]

In [ ]:
data3

    rata_rata_overdue
0        61 - 90 days
1        61 - 90 days
2         0 - 30 days
3        46 - 60 days
4        31 - 45 days
..                ...
895         > 90 days
896      46 - 60 days
897       0 - 30 days
898      31 - 45 days
899       0 - 30 days

[900 rows x 1 columns]

In [ ]:
rata = pd.get_dummies(data3)

In [ ]:
rata

,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,0,0,0,1,0
1,0,0,0,1,0
2,1,0,0,0,0
3,0,0,1,0,0
4,0,1,0,0,0
...,...,...,...,...,...
895,0,0,0,0,1
896,0,0,1,0,0
897,1,0,0,0,0
898,0,1,0,0,0
899,1,0,0,0,0

In [ ]:
dataOlah = pd.concat([aktif, rata], axis=1)

In [ ]:
dataHasil = pd.concat([data, dataOlah], axis=1)

In [ ]:
dataHasil

,Unnamed: 0,kode_kontrak,pendapatan_setahun_juta,kpr_aktif,durasi_pinjaman_bulan,jumlah_tanggungan,rata_rata_overdue,risk_rating,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,1,AGR-000001,295,YA,48,5,61 - 90 days,4,0,1,0,0,0,1,0
1,2,AGR-000011,271,YA,36,5,61 - 90 days,4,0,1,0,0,0,1,0
2,3,AGR-000030,159,TIDAK,12,0,0 - 30 days,1,1,0,1,0,0,0,0
3,4,AGR-000043,210,YA,12,3,46 - 60 days,3,0,1,0,0,1,0,0
4,5,AGR-000049,165,TIDAK,36,0,31 - 45 days,2,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,896,AGR-010739,112,YA,48,5,> 90 days,5,0,1,0,0,0,0,1
896,897,AGR-010744,120,YA,48,2,46 - 60 days,3,0,1,0,0,1,0,0
897,898,AGR-010758,166,TIDAK,24,2,0 - 30 days,1,1,0,1,0,0,0,0
898,899,AGR-010775,196,TIDAK,48,0,31 - 45 days,2,1,0,0,1,0,0,0
899,900,AGR-010790,204,TIDAK,24,2,0 - 30 days,1,1,0,1,0,0,0,0

## Normalisasi - MinMax

Rumus :

$$x'=\frac{x-xmin}{xmax-xmin}{(newMax-newMin)+newMin}$$

Data dibawah ini merupakan data x'

In [ ]:
X = dataHasil.drop(columns=['kode_kontrak','risk_rating','kpr_aktif','rata_rata_overdue'])
X

,Unnamed: 0,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,1,295,48,5,0,1,0,0,0,1,0
1,2,271,36,5,0,1,0,0,0,1,0
2,3,159,12,0,1,0,1,0,0,0,0
3,4,210,12,3,0,1,0,0,1,0,0
4,5,165,36,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
895,896,112,48,5,0,1,0,0,0,0,1
896,897,120,48,2,0,1,0,0,1,0,0
897,898,166,24,2,1,0,1,0,0,0,0
898,899,196,48,0,1,0,0,1,0,0,0
899,900,204,24,2,1,0,1,0,0,0,0

In [ ]:
from sklearn.preprocessing import MinMaxScaler

import joblib
scaler = MinMaxScaler()
#scaler.fit(features)
#scaler.transform(features)
scaled = scaler.fit_transform(X)
features_names = X.columns.copy()
#features_names.remove('label')
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features.head(10)
# scaler_filename = "scaled.save" #normalisasi di save digunakan testing
# joblib.dump(scaler, scaler_filename) 
# scaler = joblib.load(scaler_filename)

,Unnamed: 0,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,0.000000,0.978261,1.000000,0.833333,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.001112,0.873913,0.666667,0.833333,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.002225,0.386957,0.000000,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.003337,0.608696,0.000000,0.500000,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.004449,0.413043,0.666667,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
5,0.005562,0.652174,0.333333,0.833333,1.0,0.0,1.0,0.0,0.0,0.0,0.0
6,0.006674,0.000000,0.666667,0.500000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.007786,0.078261,1.000000,0.500000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
8,0.008899,0.404348,1.000000,0.833333,1.0,0.0,0.0,1.0,0.0,0.0,0.0
9,0.010011,0.130435,0.666667,1.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
testdates = pd.read_excel("https://raw.githubusercontent.com/febyfadlilah/dataset/main/credit_score.xlsx")

In [ ]:
y = testdates['risk_rating'].values
y[0:5]

array([4, 4, 1, 3, 2])

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)

LabelEncoder()

In [ ]:
ybaru = le.transform(y)

In [ ]:
ybaru

array([3, 3, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 3, 3, 0, 0, 0, 2, 4, 2, 2, 4, 2, 4, 2, 0, 2, 0, 2,
       4, 0, 2, 2, 4, 0, 2, 3, 1, 2, 1, 0, 3, 2, 2, 2, 0, 3, 0, 3, 2, 0,
       2, 4, 2, 4, 4, 4, 2, 4, 2, 0, 4, 4, 2, 2, 0, 4, 0, 0, 1, 2, 2, 3,
       0, 3, 0, 2, 2, 2, 2, 0, 1, 1, 2, 3, 3, 2, 1, 0, 2, 2, 2, 2, 3, 3,
       0, 2, 0, 1, 2, 2, 2, 4, 1, 2, 4, 2, 0, 4, 4, 0, 4, 4, 2, 1, 4, 2,
       4, 0, 1, 2, 2, 4, 4, 2, 0, 0, 0, 2, 0, 0, 4, 0, 2, 4, 2, 1, 2, 2,
       0, 0, 0, 2, 4, 2, 4, 1, 2, 2, 2, 0, 4, 2, 2, 2, 0, 0, 1, 0, 4, 2,
       2, 4, 3, 2, 3, 4, 2, 2, 4, 0, 0, 2, 2, 1, 2, 0, 1, 2, 0, 2, 1, 1,
       1, 3, 2, 1, 2, 0, 1, 4, 4, 3, 2, 0, 1, 1, 4, 3, 4, 1, 2, 2, 0, 2,
       4, 0, 1, 4, 2, 0, 4, 2, 0, 3, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 4,
       0, 2, 0, 4, 4, 3, 2, 0, 1, 2, 0, 2, 0, 3, 2, 3, 2, 2, 0, 2, 2, 4,
       1, 3, 3, 1, 0, 2, 0, 2, 2, 2, 2, 3, 0, 2, 3, 2, 0, 0, 4, 4, 0, 0,
       2, 3, 0, 1, 0, 3, 2, 2, 4, 2, 3, 0, 2, 2, 2, 3, 4, 0, 2, 4, 2, 0,
       2, 2, 2, 1, 1, 3, 0, 0, 0, 2, 2, 3, 2, 2, 4, 3, 0, 4, 3, 0, 3, 1,
       2, 0, 3, 2, 0, 3, 2, 2, 0, 2, 2, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2,
       2, 4, 0, 3, 0, 0, 2, 0, 3, 0, 0, 0, 4, 2, 2, 3, 2, 1, 0, 2, 2, 2,
       3, 2, 3, 2, 2, 2, 3, 0, 2, 4, 3, 0, 1, 1, 4, 2, 2, 2, 2, 0, 2, 3,
       2, 0, 1, 2, 0, 2, 2, 2, 0, 4, 2, 2, 4, 0, 0, 2, 1, 4, 4, 0, 2, 3,
       1, 4, 3, 1, 0, 0, 2, 1, 1, 0, 2, 2, 0, 4, 0, 2, 2, 2, 0, 3, 0, 4,
       2, 3, 3, 0, 1, 0, 1, 0, 0, 2, 1, 0, 1, 1, 3, 2, 0, 2, 3, 2, 4, 2,
       2, 4, 1, 0, 2, 0, 1, 4, 1, 2, 1, 2, 0, 0, 2, 3, 1, 3, 3, 4, 2, 2,
       2, 2, 2, 3, 1, 3, 0, 3, 2, 0, 2, 0, 3, 0, 3, 2, 0, 2, 2, 2, 3, 2,
       0, 0, 2, 2, 2, 0, 1, 1, 3, 1, 3, 0, 2, 1, 3, 0, 2, 2, 0, 3, 3, 3,
       2, 1, 2, 0, 2, 2, 0, 0, 3, 1, 2, 3, 2, 3, 3, 4, 2, 2, 0, 2, 1, 4,
       4, 1, 2, 2, 4, 1, 3, 0, 2, 4, 4, 3, 2, 2, 0, 4, 0, 2, 1, 1, 1, 2,
       2, 4, 2, 2, 1, 2, 1, 2, 0, 2, 2, 3, 2, 2, 1, 3, 4, 2, 0, 1, 3, 2,
       0, 3, 2, 0, 2, 1, 1, 0, 0, 3, 2, 1, 2, 1, 0, 3, 3, 2, 1, 4, 0, 2,
       4, 2, 2, 3, 0, 2, 2, 0, 3, 0, 2, 0, 0, 2, 2, 0, 4, 3, 3, 1, 2, 4,
       1, 2, 0, 0, 0, 1, 4, 0, 3, 0, 1, 3, 4, 4, 1, 3, 4, 2, 1, 3, 0, 2,
       2, 1, 2, 4, 0, 3, 4, 2, 0, 1, 0, 0, 2, 2, 4, 2, 2, 3, 3, 2, 3, 2,
       2, 0, 2, 0, 0, 0, 0, 2, 4, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 3, 0, 1,
       2, 0, 2, 4, 2, 3, 0, 2, 0, 3, 0, 0, 3, 2, 2, 2, 0, 0, 2, 3, 3, 0,
       0, 4, 3, 3, 3, 2, 2, 2, 0, 1, 2, 3, 1, 2, 3, 3, 3, 0, 3, 3, 0, 2,
       3, 2, 1, 3, 2, 3, 2, 4, 2, 2, 4, 0, 1, 0, 2, 0, 3, 3, 0, 0, 2, 4,
       0, 1, 2, 0, 1, 1, 4, 2, 1, 2, 2, 4, 2, 4, 2, 3, 0, 2, 3, 4, 0, 3,
       2, 4, 4, 3, 2, 2, 4, 2, 3, 1, 2, 2, 3, 0, 0, 0, 2, 1, 0, 2, 0, 1,
       2, 4, 0, 0, 2, 0, 1, 4, 2, 4, 2, 3, 2, 4, 0, 4, 2, 0, 1, 0])

pembagian data test mempengaruhi akurasi,semakin banyak data maka mesin semakin peka

## Train to Naive Bayes Gaussian Model

In [ ]:
# library for Naive Bayes Gaussian
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.preprocessing import LabelEncoder

#Model Select
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

#train = data latih & test = data uji
#train_size dan test_size jika di jumlah harus = 1
training, test = train_test_split(scaled, train_size = 0.8, test_size = 0.2, shuffle=False)
training_label, test_label = train_test_split(ybaru, train_size = 0.8, test_size = 0.2, shuffle=False)

clf2 = GaussianNB()
clf2.fit(training, training_label)

probas = clf2.predict_proba(test)
probas = probas[:,1]
probas.shape

probas

test_label

array([4, 2, 1, 3, 0, 2, 2, 1, 2, 4, 0, 3, 4, 2, 0, 1, 0, 0, 2, 2, 4, 2,
       2, 3, 3, 2, 3, 2, 2, 0, 2, 0, 0, 0, 0, 2, 4, 2, 1, 2, 2, 2, 1, 1,
       2, 2, 1, 3, 0, 1, 2, 0, 2, 4, 2, 3, 0, 2, 0, 3, 0, 0, 3, 2, 2, 2,
       0, 0, 2, 3, 3, 0, 0, 4, 3, 3, 3, 2, 2, 2, 0, 1, 2, 3, 1, 2, 3, 3,
       3, 0, 3, 3, 0, 2, 3, 2, 1, 3, 2, 3, 2, 4, 2, 2, 4, 0, 1, 0, 2, 0,
       3, 3, 0, 0, 2, 4, 0, 1, 2, 0, 1, 1, 4, 2, 1, 2, 2, 4, 2, 4, 2, 3,
       0, 2, 3, 4, 0, 3, 2, 4, 4, 3, 2, 2, 4, 2, 3, 1, 2, 2, 3, 0, 0, 0,
       2, 1, 0, 2, 0, 1, 2, 4, 0, 0, 2, 0, 1, 4, 2, 4, 2, 3, 2, 4, 0, 4,
       2, 0, 1, 0])

In [ ]:
probas = probas.round()
probas

array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [ ]:
#data latih / training
print('Data Training : ',training.shape)
print('Data Testing : ',test.shape)

Data Training :  (720, 11)
Data Testing :  (180, 11)

In [ ]:
print('Accuracy Setelah Normalisasi : ',accuracy_score(test_label, probas))

Accuracy Setelah Normalisasi :  0.35555555555555557