#UAS - Prediksi Jenis Obat

In [ ]:
import pandas as pd

Read Data

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/febyfadlilah/dataset/main/drug200.csv")
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

Exploration Data

In [ ]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
df[["Age","Na_to_K"]].agg(['min','max'])
# df[["precipitation", "temp_max", "temp_min", "wind"]].agg(['min','max'])

     Age  Na_to_K
min   15    6.269
max   74   38.247

In [ ]:
df.Drug.value_counts()

DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64

Preprocessing Data

Normalize Data

In [ ]:
data2 = df[["Sex"]]
data2

    Sex
0     F
1     M
2     M
3     F
4     F
..   ..
195   F
196   M
197   M
198   M
199   F

[200 rows x 1 columns]

In [ ]:
jk = pd.get_dummies(data2)
jk

     Sex_F  Sex_M
0        1      0
1        0      1
2        0      1
3        1      0
4        1      0
..     ...    ...
195      1      0
196      0      1
197      0      1
198      0      1
199      1      0

[200 rows x 2 columns]

In [ ]:
data3 = df[["BP"]]
data3

         BP
0      HIGH
1       LOW
2       LOW
3    NORMAL
4       LOW
..      ...
195     LOW
196     LOW
197  NORMAL
198  NORMAL
199     LOW

[200 rows x 1 columns]

In [ ]:
tekanan = pd.get_dummies(data3)
tekanan

     BP_HIGH  BP_LOW  BP_NORMAL
0          1       0          0
1          0       1          0
2          0       1          0
3          0       0          1
4          0       1          0
..       ...     ...        ...
195        0       1          0
196        0       1          0
197        0       0          1
198        0       0          1
199        0       1          0

[200 rows x 3 columns]

In [ ]:
data4 = df[["Cholesterol"]]
data4

    Cholesterol
0          HIGH
1          HIGH
2          HIGH
3          HIGH
4          HIGH
..          ...
195        HIGH
196        HIGH
197        HIGH
198      NORMAL
199      NORMAL

[200 rows x 1 columns]

In [ ]:
kolestrol = pd.get_dummies(data4)
kolestrol

     Cholesterol_HIGH  Cholesterol_NORMAL
0                   1                   0
1                   1                   0
2                   1                   0
3                   1                   0
4                   1                   0
..                ...                 ...
195                 1                   0
196                 1                   0
197                 1                   0
198                 0                   1
199                 0                   1

[200 rows x 2 columns]

In [ ]:
dataOlah = pd.concat([jk,tekanan,kolestrol], axis=1)

In [ ]:
dataHasil = pd.concat([df,dataOlah], axis = 1)
dataHasil

,Age,Sex,BP,Cholesterol,Na_to_K,Drug,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL
0,23,F,HIGH,HIGH,25.355,DrugY,1,0,1,0,0,1,0
1,47,M,LOW,HIGH,13.093,drugC,0,1,0,1,0,1,0
2,47,M,LOW,HIGH,10.114,drugC,0,1,0,1,0,1,0
3,28,F,NORMAL,HIGH,7.798,drugX,1,0,0,0,1,1,0
4,61,F,LOW,HIGH,18.043,DrugY,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,56,F,LOW,HIGH,11.567,drugC,1,0,0,1,0,1,0
196,16,M,LOW,HIGH,12.006,drugC,0,1,0,1,0,1,0
197,52,M,NORMAL,HIGH,9.894,drugX,0,1,0,0,1,1,0
198,23,M,NORMAL,NORMAL,14.020,drugX,0,1,0,0,1,0,1
199,40,F,LOW,NORMAL,11.349,drugX,1,0,0,1,0,0,1

In [ ]:
X = dataHasil.drop(columns=["Drug","Sex","BP","Cholesterol"])
y = dataHasil.Drug

In [ ]:
X

,Age,Na_to_K,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL
0,23,25.355,1,0,1,0,0,1,0
1,47,13.093,0,1,0,1,0,1,0
2,47,10.114,0,1,0,1,0,1,0
3,28,7.798,1,0,0,0,1,1,0
4,61,18.043,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...
195,56,11.567,1,0,0,1,0,1,0
196,16,12.006,0,1,0,1,0,1,0
197,52,9.894,0,1,0,0,1,1,0
198,23,14.020,0,1,0,0,1,0,1
199,40,11.349,1,0,0,1,0,0,1

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)
y

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

In [ ]:
le.inverse_transform(y)

array(['DrugY', 'drugC', 'drugC', 'drugX', 'DrugY', 'drugX', 'DrugY',
       'drugC', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'DrugY', 'drugX', 'drugA', 'drugC', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'DrugY', 'drugX', 'drugB', 'drugX', 'DrugY', 'drugX',
       'drugX', 'drugA', 'drugX', 'drugX', 'drugX', 'DrugY', 'drugB',
       'DrugY', 'drugX', 'drugX', 'drugX', 'drugA', 'drugC', 'DrugY',
       'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugB', 'drugC',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugA', 'DrugY',
       'drugX', 'drugB', 'DrugY', 'drugA', 'drugX', 'DrugY', 'DrugY',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugA',
       'DrugY', 'drugA', 'drugX', 'drugB', 'drugX', 'drugC', 'drugA',
       'drugC', 'drugB', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'drugA', 'drugA', 'drugC', 'drugX', 'DrugY',
       'drugX', 'drugX', 'DrugY', 'drugB', 'DrugY', 'drugA', 'drugX',
       'drugX', 'drugX', 'drugX', 'DrugY', 'drugX', 'drugX', 'drugA',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugB', 'DrugY',
       'DrugY', 'drugX', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'DrugY', 'drugX', 'drugB', 'drugA', 'drugB', 'drugX',
       'drugA', 'DrugY', 'drugB', 'DrugY', 'drugA', 'drugX', 'drugX',
       'drugA', 'drugX', 'drugC', 'drugA', 'drugB', 'drugX', 'drugX',
       'DrugY', 'drugC', 'drugA', 'DrugY', 'drugC', 'drugX', 'drugX',
       'drugB', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'drugA', 'drugX', 'drugX', 'DrugY', 'DrugY', 'drugA',
       'DrugY', 'drugA', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugB', 'drugA', 'DrugY',
       'DrugY', 'DrugY', 'drugA', 'DrugY', 'drugC', 'DrugY', 'drugC',
       'drugC', 'drugX', 'drugX', 'drugX'], dtype=object)

In [ ]:
labels = pd.get_dummies(dataHasil.Drug).columns.values.tolist()
labels

['DrugY', 'drugA', 'drugB', 'drugC', 'drugX']

Normalisasi MinMax Scaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[0.13559322, 0.59684783, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.54237288, 0.21339671, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.54237288, 0.12023891, 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.62711864, 0.11335918, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.13559322, 0.24238539, 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.42372881, 0.15885922, 1.        , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
X.shape, y.shape

((200, 9), (200,))

Split Data

In [ ]:
# membagi data menjadi data testing(20%) dan training(80%)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((160, 9), (40, 9), (160,), (40,))

KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from numpy import array
metode1 = KNeighborsClassifier(n_neighbors=3)
metode1.fit(X_train, y_train)
print(metode1.score(X_train, y_train))
print(metode1.score(X_test, y_test))
y_pred = metode1.predict(scaler.transform(array([[0.13,0.51,1,0,0,1,0,1,0]])))
le.inverse_transform(y_pred)[0]

0.925
0.775

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

'drugC'

Gaussian Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

metode2 = GaussianNB()
metode2.fit(X_train, y_train)
print(metode2.score(X_train, y_train))
print(metode2.score(X_test, y_test))
y_pred = metode2.predict(array([[0.13,0.51,1,0,0,1,0,1,0]]))
le.inverse_transform(y_pred)[0]

0.7
0.7

'drugC'

Decission Tree

In [ ]:
from sklearn import tree

metode3 = tree.DecisionTreeClassifier(criterion="gini")
metode3.fit(X_train, y_train)
print(metode3.score(X_train, y_train))
print(metode3.score(X_test, y_test))
y_pred = metode3.predict(array([[0.13,0.51,1,0,0,1,0,1,0]]))
le.inverse_transform(y_pred)[0]

1.0
0.95

'DrugY'

Export 



*   Label Encoder
*   Scaler
*   Model

In [ ]:
from sklearn.utils.validation import joblib
# label encoder
joblib.dump(le, "le.save") 

# scaler
joblib.dump(scaler, "scaler.save") 

# model
joblib.dump(metode1, "nb.joblib")
joblib.dump(metode2, "knn.joblib")
joblib.dump(metode3, "tree.joblib")

['tree.joblib']